### ISSUE TITLE
Output type definition breaks syntax highlighting

### ISSUE THREAD

**Issue by kuuup** [tptee/FlowIDE#9]
Hi :smile: 

I'm not sure if this is a flowide (or maybe babel-sublime) issue but syntax highlighting is broken when I define the output type of a class instance field method.

![screenshot_20161208_204517](https://cloud.githubusercontent.com/assets/983015/21025200/d31f8848-bd87-11e6-83fb-7f877477c6ad.png)

**Comment by tptee** [comment]
Hi there! I'm pretty sure this is an issue with `babel-sublime`, since the plugin doesn't touch syntax highlighting. I could reproduce this with FlowIDE disabled.
